[build-system]
requires = ["setuptools>=61.0"]
build-backend = "setuptools.build_meta"

[project]
name = "instadownloader"
version = "0.1.1"
description = "Download posts from Instagram"
readme = "README.md"
requires-python = ">=3.8"

dependencies = [
"aiohttp",
"aiohttp_socks",
"aiofiles",
]
[project.scripts]
instadownloader = "instadownloader.insta:main"

[tool.setuptools.packages.find]
where = ["."]
include = ["instadownloader*"]